### ISSUE TITLE
No Slack Travis Notifications

### ISSUE THREAD

**Issue by jfnw-capco** [capcodigital/ideafunnel#14]
### Expected Behaviour

It was expected that the Travis build status would be visible in the slack channel.

### Actual Behaviour

There are no notifications being seen in slack against the Idea Funnel channel

### Steps to Reproduce the Issue

Trigger a build and review the Slack Idea Funnel channel

**Comment by jfnw-capco** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Identify the source of duplicate infrastructure being created](https://trello.com/c/cRWEbOyY/49-identify-the-source-of-duplicate-infrastructure-being-created)

**Comment by manu-capco** [comment]
Fixed. Ran the "travis encrypt "capcooss:{{KEY_DELETED}}#ideafunnel" --add notifications.slack -r capcodigital/ideafunnel" command from the folder containing .travis.yml and pushed the changed file.
