### ISSUE TITLE
Hardcoded docker tag 1524511151

### ISSUE THREAD

**Issue by jfnw-capco** [capcodigital/ideafunnel#30]
### Expected Behaviour

It is expected that the docker image tag that is created when the the image is built is used to create the infrastructure.  However the image tag to use has been hard coded in .travis.sh. 

### Actual Behaviour

Also uses 1524511151 as this is hard coded in the docker compose file that is being used to create the production infrastructure

### Steps to Reproduce the Issue

You can confirm this by running docker images command on the droplet

**Comment by manu-capco** [comment]
Removed use of docker tag to use dynamic $APP_TAG environment variable
